const translations = {'antiques & collectibles': 'Antiquitäten & Sammlerstücke',
'architecture': 'Architektur',
'art': 'Kunst',
'bibles': 'Bibel',
'biography & autobiography': 'Biographie & Autobiographie',
'body, mind & spirit': 'Körper, Geist und Seele',
'business & economics': 'Business & Wirtschaft',
'comics & graphic novels': 'Comics & Graphic Novels',
'computers': 'Computer',
'cooking': 'Kochen',
'crafts & hobbies': 'Handwerk & Hobby',
'design': 'Design',
'drama': 'Drama',
'education': 'Bildung',
'family & relationships': 'Familie & Beziehungen',
'fiction': 'Belletristik',
'foreign language study': 'Fremdsprachenstudium',
'games & activities': 'Spiel & Freizeit',
'gardening': 'Garten',
'health & fitness': 'Gesundheit & Fitness',
'history': 'Geschichte',
'house & home': 'Haus & Heim',
'humor': 'Humor',
'juvenile fiction': 'Kinderbücher',
'juvenile nonfiction': 'Sachbucher für Kinder',
'language arts & disciplines': 'Sprachwissenschaften',
'law': 'Recht',
'literary collections': 'Literatursammlungen',
'literary criticism': 'Literaturkritik',
'mathematics': 'Mathematik',
'medical': 'Medizin',
'music': 'Musik',
'nature': 'Natur',
'performing arts': 'Darstellende Künste',
'pets': 'Haustiere',
'philosophy': 'Philosophie',
'photography': 'Photographie',
'poetry': 'Lyrik',
'political science': 'Politikwissenschaft',
'psychology': 'Psychologie',
'reference': 'Nachschlagewerke',
'religion': 'Religion',
'science': 'Naturwissenschaften',
'self-help': 'Selbsthilfe',
'social science': 'Sozialwissenschaften',
'sports & recreation': 'Sport & Freizeit',
'study aids': 'Studium',
'technology & engineering': 'Technik & Ingenieurwesen',
'transportation': 'Verkehr',
'travel': 'Reisen',
'true crime': 'True Crime',
'young adult fiction': 'Jugendliteratur',
'young adult nonfiction': 'Sachbücher für junge Erwachsene'}

const translateCategory = term => translations[term.toLowerCase()] ?? term